#!/usr/bin/env python

# File name: 		projecteuler002.py
# Author: 			Matt McGranaghan
# Date Created:		2014/04/11
# Date Modified: 	2014/04/11
# Python Version: 	2.7

# Each new term in the Fibonacci sequence is generated by adding the previous  two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib(a,b):
	new_a = b
	new_b = a + b
	return new_a, new_b

def solution002():

	max_x = 4000000
	sum_even = 0
	a = 1
	b = 2

	while b < max_x:
		if (b % 2) == 0:
			sum_even += b
		a, b = fib(a,b)

	return sum_even

print solution002()